name: servidor_dart
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  socket_io: ^0.9.4
  mongo_dart: ^0.4.4

dev_dependencies:
  pedantic: ^1.9.0
